[TASK 3] added checking on valid data and bike ID
iprisakaru/iTechArtLabs pull request #4
Opened 2021-08-03 16:47 UTC by iprisakaru

1) Added checking time and data on conformity to type "YYYY-MM-DD HH:MM:SS"
2) Added checking bike ID on conformity to type " letter + 6 numbers "

2021-08-04 08:23 UTC, alexander-belyaev requested changes

2021-08-04 08:23 UTC, alexander-belyaev commented on README.md
> -- **Technology:**
Why did you decide to remove Readme.md?

2021-08-04 08:23 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +      if (line.length != 9 || !isDataValid(line(1)) || !isDataValid(line(2)) || !isBikeIDValid(line(7))) Left(new IllegalArgumentException) else Right(Trip(line(0).toInt, line(1), line(2), line(3).to
Could you clarify what does 1, 2, 3 indexes here mean?

2021-08-04 08:23 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +    val a = isBikeIDValid("W35343")
Wrong variable naming
Please check the following article:
https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29

2021-08-04 08:23 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +  def isDataValid(line : String): Boolean={
Please fix formatting near braces

2021-08-04 08:23 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +  def isBikeIDValid(line : String): Boolean={
Formmatting

2021-08-04 08:27 UTC, iprisakaru commented on src/main/scala/by/bsu/FileService.scala
> +    val a = isBikeIDValid("W35343")
I just checked how my function work. I'll delete this line.

2021-08-04 08:32 UTC, iprisakaru commented on src/main/scala/by/bsu/FileService.scala
> +      if (line.length != 9 || !isDataValid(line(1)) || !isDataValid(line(2)) || !isBikeIDValid(line(7))) Left(new IllegalArgumentException) else Right(Trip(line(0).toInt, line(1), line(2), line(3).to
I am given a string as input. I split it into an array of strings. And each element of the array is some kind of class field.

2021-08-06 08:28 UTC, alexander-belyaev approved these changes

2021-08-06 09:24 UTC, merged