[TASK 1] added writting data to db
iprisakaru/iTechArtLabs pull request #9
Opened 2021-08-24 23:56 UTC by iprisakaru

Added extracting data from files in repository.

2021-08-25 07:40 UTC, alexander-belyaev requested changes

2021-08-25 07:40 UTC, alexander-belyaev commented on build.sbt
> +libraryDependencies += "com.typesafe.slick" %% "slick" % "3.3.3"
Try to define all your dependencies together

You could define them at any point of time in build.sbt, but it's just harder to maintain

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +  def readFileWithFormat(fileName: String) = {
Why not to keep a method result type?

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +        case supportedTypes.typeXLSX => Future(ReadFile.readFileXlsx(fileName))
What if the file has no extension?
What if the file has extension .data but actually has data in csv format inside?

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +    LOGGER.info(s"${paths.length} correct file(s) were found")
if "paths" collection stores filenames, why not to name it "filenames"?

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/Main.scala
> +  case class Data(userID: Int, duration: Int, startDate: String, endDate: String,
If you double-check Scala Naming Convention (https://docs.scala-lang.org/style/naming-conventions.html), you'll notice a mistake in the field naming

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/ReadFile.scala
> +  val numberOfParams = 10
Do you think these constants are more tightly related to each other than the parsing methods?
Are there any problems for readFileXlsx/ readFileCsv methods to read a file with swapped columns? What do you need to change in the code to easily support it?

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/ReadFile.scala
> +  val posOfBikeID = 8
Naming

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/ReadFile.scala
> +    val tmpUser = new UserDAO(config)
Could you explain what should "tmpUser" variable name mean for your collegues?

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/ReadFile.scala
> +    val wrUsers = Future.sequence(listOfTrips.flatMap(_.toOption).map(_.userID).map(line => tmpUser.insertUniq(User(None, line))))
You're likely to fire crazy amount of INSERT statements to the database. 
Are there any ways to make a bulk insert instead?

What would happen if you process the same file twice?

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def find(id: Int): Future[Option[Bike]] = {
is it findById?

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def findByCode(code: String): Future[Option[Bike]] = {
Is code unique?

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def insertUniq(bike: Bike): Future[Either[String, Future[Bike]]] = {
result time must not contain Future inside Future - it doesn't make sense
it should be just Future[Either[String,Bike]]
Also, with slick you could do it in single SQL statement to the database (2 queries currently)

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/db/DAO/StationDAO.scala
> +  def insert(station: Station): Future[Station] = {
It sounds to me StationDAO.insert is a copy-paste of BikeDAO.insert with minor differences.
Try to generalize CRUD operations in DAO

2021-08-25 07:40 UTC, alexander-belyaev commented on src/main/scala/by/bsu/db/DAO/TripDAO.scala
> +    val checkBikes = db.run(bikes.filter(_.code === bike_code).result.headOption)
Wow, 4 queries to the database - it will work extremely slow

a) Trip DAO can't fire requests to other tables than Trips
b) You could still use SQL Joins with slick to get required data in one go

2021-08-25 10:04 UTC, iprisakaru commented on src/main/scala/by/bsu/FileService.scala
> +        case supportedTypes.typeXLSX => Future(ReadFile.readFileXlsx(fileName))
If the file has no extension or the extension is incorrect, then a warning will be displayed in the logger and the program will continue to run.

2021-08-25 10:07 UTC, iprisakaru commented on src/main/scala/by/bsu/ReadFile.scala
> +    val tmpUser = new UserDAO(config)
I'll correct it. It's mean temporary variable name

2021-08-25 10:10 UTC, iprisakaru commented on src/main/scala/by/bsu/ReadFile.scala
> +    val wrUsers = Future.sequence(listOfTrips.flatMap(_.toOption).map(_.userID).map(line => tmpUser.insertUniq(User(None, line))))
1) So far, I only have one line insertion.  
2) If we run the same file with the same data twice, then the logger will receive a warning that such data already exists.

2021-08-25 10:12 UTC, iprisakaru commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def find(id: Int): Future[Option[Bike]] = {
Yes, it is.

2021-08-25 10:13 UTC, iprisakaru commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def findByCode(code: String): Future[Option[Bike]] = {
What do u mean?

2021-08-25 10:14 UTC, iprisakaru commented on src/main/scala/by/bsu/FileService.scala
> +  def readFileWithFormat(fileName: String) = {
I'll add it

2021-08-25 10:18 UTC, iprisakaru commented on src/main/scala/by/bsu/ReadFile.scala
> +  val numberOfParams = 10
As for the columns, there is a strict order.  I can add column names to the first line, and read this line, and from it I can understand in what order the columns are arranged.

2021-08-25 10:33 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +  def readFileWithFormat(fileName: String) = {
Scala allows not to define result type manually, but sometimes it's better to do it from a readability point of view. Especially when the result type is quite complex.
Also, what does Int mean in that tupple?

2021-08-25 10:34 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +        case supportedTypes.typeXLSX => Future(ReadFile.readFileXlsx(fileName))
Is it possible to try to process it as regular CVS just in case? It worst case, it won't work
In the best case, invalid file extension won't matter as long as the file structure itself is valid

2021-08-25 10:34 UTC, alexander-belyaev commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def find(id: Int): Future[Option[Bike]] = {
Could you rename the method in this case?

2021-08-25 10:35 UTC, alexander-belyaev commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def findByCode(code: String): Future[Option[Bike]] = {
Is the code column in the "bikes" table unique or several bikes could share the same code?

2021-08-25 10:35 UTC, iprisakaru commented on src/main/scala/by/bsu/FileService.scala
> +  def readFileWithFormat(fileName: String) = {
Ok, I understood. 

Int means number of exceptions.

2021-08-25 10:38 UTC, iprisakaru commented on src/main/scala/by/bsu/FileService.scala
> +        case supportedTypes.typeXLSX => Future(ReadFile.readFileXlsx(fileName))
Ok, I just thought it was a user problem to specify the correct permissions.  I will add this processing.

2021-08-25 10:39 UTC, iprisakaru commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def find(id: Int): Future[Option[Bike]] = {
Yes, I can

2021-08-25 10:52 UTC, iprisakaru commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def findByCode(code: String): Future[Option[Bike]] = {
Think that several bikes can share the same code.

2021-08-29 19:34 UTC, iprisakaru commented on src/main/scala/by/bsu/db/DAO/BikeDAO.scala
> +  def findByCode(code: String): Future[Option[Bike]] = {
I'm confused, we are looking for only one (first) bike by ID.

2021-08-30 07:56 UTC, alexander-belyaev approved these changes

2021-08-30 07:56 UTC, alexander-belyaev commented on src/main/scala/by/bsu/FileService.scala
> +  type Futures = Future[List[List[Any]]]
Hm, let's discuss it in voice

2021-08-30 08:27 UTC, merged